// <auto-generated />
using System;
using EmployeeManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeManager.Migrations
{
    [DbContext(typeof(EmployeeManagerDBContext))]
    partial class EmployeeManagerDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeManager.Models.Employee", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeeEmail")
                        .IsRequired();

                    b.Property<string>("EmployeeDepartment")
                        .IsRequired();

                    b.Property<DateTime>("EmployeeBirthDate");

                    b.Property<string>("EmployeeFirstName")
                        .IsRequired();
                    
                    b.Property<string>("EmployeeLastName")
                        .IsRequired();

                    b.HasKey("ItemId");

                    b.ToTable("Employee");
                });
            
            modelBuilder.Entity("EmployeeManager.Models.Department", b =>
            {
                b.Property<int>("DepartmentId")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("DepartmenName")
                    .IsRequired();

                b.Property<int>("MaxEmployees")
                    .IsRequired();

                b.HasKey("DepartmentId");

                b.ToTable("Department");
            });
#pragma warning restore 612, 618
        }
    }
}
